name: Build
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
      - run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git remote set-url origin https://${GITHUB_ACTOR}:${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}
          git fetch --all
      - run: echo "::set-env name=BUILD_PATH::$(mktemp -d)"
        name: Generate build directory
      - run: |
          yarn install
          yarn run build
      - run: cp dist/* $BUILD_PATH -r
      - run: git checkout -b gh-pages origin/gh-pages
      - run: |
          rm -rf ./*
          mv ${BUILD_PATH}/* .
          rm -rf ${BUILD_PATH}
      - run: |
          git add *
          git commit -am "Deploy"
          git push --force